runtime: python27
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /(.+)
    secure: always
    static_files: app/\1
    upload: app/.*
  - url: /
    secure: always
    static_files: app/index.html
    upload: app/index.html
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: paul-tiller@appspot.gserviceaccount.com