runtime: python27
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /(.+)
    secure: always
    application_readable: false
    static_files: app/\1
    require_matching_file: false
    upload: app/.*
  - url: /
    secure: always
    application_readable: false
    static_files: app/index.html
    require_matching_file: false
    upload: app/index.html
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}