runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.+)
  static_files: app/\1
  upload: app/.*
  secure: always

- url: /
  static_files: app/index.html
  upload: app/index.html
  secure: always